# Generated by Django 6.1.1 on 2026-09-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
