# Generated by Django 6.1.1 on 2026-09-23 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0002_userorm_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatCanceladoORM",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rfc", models.CharField(max_length=50, unique=True)),
                ("razon_social", models.TextField()),
                (
                    "tipo_persona",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("supuesto", models.TextField()),
                ("fecha_de_cancelacion", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=20)),
                ("fecha_de_publicacion", models.DateField()),
                (
                    "entidad_federativa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "sat_cancelados",
            },
        ),
        migrations.CreateModel(
            name="SatHistoryORM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="processing",
                        max_length=16,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("record_number", models.IntegerField(default=0)),
                ("omitted_number", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sat_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sat_history",
                "ordering": ["-started_at"],
            },
        ),
    ]
